version: "3.4"

services:
  node:
    image: node:16-alpine
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    restart: always
    volumes:
      - .:/usr/src/app
    links:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    container_name: elasticsearch
    environment:
      discovery.seed_hosts: elasticsearch
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: password
      network.host: 0
      xpack.security.enabled: 'false'
      xpack.security.http.ssl.enabled: 'false'
      xpack.security.http.ssl.client_authentication: optional
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.3
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "https://elasticsearch:9200"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      - node
    networks:
      - elk
  postgres:
    image: postgres:14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  keycloak:
    image: jboss/keycloak:16.1.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_PORT: 5432
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./keycloak-themes/admin:/opt/jboss/keycloak/themes/admin/

volumes:
  esdata1:
  postgres_data:
    driver: local

networks:
  elk:
    driver: bridge
